import cv2
image = cv2.imread('mess up pic.png')
gray = cv2.cvtColor(image, 0)
dobelx = cv2.Sobel(gray, cv2.CV_64F, 1, 0,)
dobely = cv2.Sobel(gray, cv2.CV_64F, 0, 1)
sobelx = cv2.convertScaleAbs(dobelx)
sobely = cv2.convertScaleAbs(dobely)
sobelxy = cv2.bitwise_or(sobelx, sobely)
sobelxy =cv2.convertScaleAbs(sobelxy)
cv2.imshow('original image', image)
cv2.imshow('sobelx', sobelx)
cv2.imshow('sobely', sobely)
cv2.imshow('sobelxy using sobel() function', sobelxy)
cv2.waitKey(0)
cv2.destroyAllWindows()