import cv2
from matplotlib import pyplot as plt
image = cv2.imread('picture test.jpg')
color = ('Blue','Green','Red')
histBlue = cv2.calcHist([image],[0],None,[256],[0,256])
histGreen = cv2.calcHist([image],[1],None,[256],[0,256])
histRed = cv2.calcHist([image],[2],None,[256],[0,256])
plt.subplot(3,1,1)
plt.plot(histBlue,color = 'Blue')
plt.title('Blue hist')
plt.subplot(3,1,2)
plt.plot(histGreen,color = 'Green')
plt.title('Green hist')
plt.subplot(3,1,3)
plt.plot(histRed,color = 'Red')
plt.title('Red hist')
plt.suptitle('loaded image hist')
plt.show()
cv2.imshow('loaded image', image)
cv2.waitKey(0)
